class Var(object):
    APP_ID = int(get("APP_ID", 6))
    API_HASH = get("API_HASH", "eb06d4abfb49dc3eeb1aeb98ae0f581e")
    STR1 = get("STRING_SESSION", None)
    STR2 = get("STR2", None)
    STR3 = get("STR3", None)
    STR4 = get("STR4", None)
    DB_URI = get("DATABASE_URL", None)
    TEMP_DOWNLOAD_DIRECTORY = get("TEMP_DOWNLOAD_DIRECTORY", "./User_Drive")
    TMP_DOWNLOAD_DIRECTORY = get("TEMP_DOWNLOAD_DIRECTORY", "./User_Drive")
    CUSTOM_CMD = get("CUSTOM_CMD", ".")
    LOGGER = True
    GITHUB_ACCESS_TOKEN = get("GITHUB_ACCESS_TOKEN", None)
    GIT_REPO_NAME = get("GIT_REPO_NAME", None)
    SUDO_USERS = set(int(x) for x in get("SUDO_USERS", "779890498").split())
    SUDO_USERS1 = set(
        int(x) for x in get("SUDO_USERS1", "779890498").split()
    )
    SUDO_USERS2 = set(
        int(x) for x in get("SUDO_USERS2", "779890498").split()
    )
    SUDO_USERS3 = set(
        int(x) for x in get("SUDO_USERS3", "779890498").split()
    )
    SUDO_USERS4 = set(
        int(x) for x in get("SUDO_USERS4", "779890498").split()
    )
    WHITELIST_USERS = set(
        int(x) for x in get("WHITELIST_USERS", "779890498").split()
    )
    BLACKLIST_USERS = set(int(x) for x in get("BLACKLIST_USERS", "").split())
    DEVLOPERS = set(int(x) for x in get("DEVLOPERS", "779890498").split())
    OWNER_ID = set(int(x) for x in get("OWNER_ID", "779890498").split())
    SUPPORT_USERS = set(int(x) for x in get("SUPPORT_USERS", "").split())
    PLUGIN_CHANNEL = int(get("BOTLOG_CHATID", None))
    LYDIA_API_KEY = get("LYDIA_API_KEY", None)
    HEROKU_API_KEY = get("HEROKU_API_KEY", None)
    HEROKU_APP_NAME = get("HEROKU_APP_NAME", None)
    TG_BOT_TOKEN_BF_HER = get("TG_BOT_TOKEN_BF_HER", None)
    TG_BOT_USER_NAME_BF_HER = get("TG_BOT_USER_NAME_BF_HER", None)
    DOWNLOAD_PFP_URL_CLOCK = get("DOWNLOAD_PFP_URL_CLOCK", None)
    G_DRIVE_CLIENT_ID = get("G_DRIVE_CLIENT_ID", None)
    G_DRIVE_CLIENT_SECRET = get("G_DRIVE_CLIENT_SECRET", None)
    GDRIVE_FOLDER_ID = get("GDRIVE_FOLDER_ID", "root")
    UB_BLACK_LIST_CHAT = set(
        int(x) for x in get("UB_BLACK_LIST_CHAT", "").split()
    )
    AUTH_TOKEN_DATA = get("AUTH_TOKEN_DATA", None)
    if AUTH_TOKEN_DATA is not None:
        if not os.path.isdir(TMP_DOWNLOAD_DIRECTORY):
            os.makedirs(TMP_DOWNLOAD_DIRECTORY)
        t_file = open(TMP_DOWNLOAD_DIRECTORY + "auth_token.txt", "w")
        t_file.write(AUTH_TOKEN_DATA)
        t_file.close()
    BOTLOG_CHATID = get("BOTLOG_CHATID", None)

    # +++++++++++++++++++++++++++|BORG_CONFIG|+++++++++++++++++++++++++++#
    LOGGER = True
    LOCATION = get("LOCATION", None)
    OPEN_WEATHER_MAP_APPID = get("OPEN_WEATHER_MAP_APPID", None)
    SCREEN_SHOT_LAYER_ACCESS_KEY = get("SCREEN_SHOT_LAYER_ACCESS_KEY", None)
    PRIVATE_GROUP_BOT_API_ID = int(get("BOTLOG_CHATID", None))
    PRIVATE_CHANNEL_BOT_API_ID = int(get("BOTLOG_CHATID", None))
    TMP_DOWNLOAD_DIRECTORY = get("TMP_DOWNLOAD_DIRECTORY", "./User_Drive")
    IBM_WATSON_CRED_URL = get("IBM_WATSON_CRED_URL", None)
    IBM_WATSON_CRED_PASSWORD = get("IBM_WATSON_CRED_PASSWORD", None)
    TELEGRAPH_SHORT_NAME = get("TELEGRAPH_SHORT_NAME", "X-Tra-Telegram")
    OCR_SPACE_API_KEY = get("OCR_SPACE_API_KEY", None)
    G_BAN_LOGGER_GROUP = int(get("BOTLOG_CHATID", None))
    GOOGLE_SEARCH_COUNT_LIMIT = int(get("GOOGLE_SEARCH_COUNT_LIMIT", 9))
    TG_GLOBAL_ALBUM_LIMIT = int(get("TG_GLOBAL_ALBUM_LIMIT", 9))
    TG_BOT_TOKEN_BF_HER = get("TG_BOT_TOKEN_BF_HER", None)
    TG_BOT_USER_NAME_BF_HER = get("TG_BOT_USER_NAME_BF_HER", None)
    NO_SONGS = bool(get("NO_SONGS", False))
    MAX_MESSAGE_SIZE_LIMIT = 4095
    UB_BLACK_LIST_CHAT = set(
        int(x) for x in get("UB_BLACK_LIST_CHAT", "").split()
    )
    MAX_ANTI_FLOOD_MESSAGES = 10
    ANTI_FLOOD_WARN_MODE = ChatBannedRights(
        until_date=None, view_messages=None, send_messages=True
    )
    # chat ids or usernames, it is recommended to use chat ids,
    CHATS_TO_MONITOR_FOR_ANTI_FLOOD = []
    REM_BG_API_KEY = get("REM_BG_API_KEY", None)
    SLAP_USERNAME = get("SLAP_USERNAME", None)
    GITHUB_ACCESS_TOKEN = get("GITHUB_ACCESS_TOKEN", None)
    GIT_REPO_NAME = get("GIT_REPO_NAME", None)
    NO_P_M_SPAM = bool(get("NO_P_M_SPAM", False))
    MAX_FLOOD_IN_P_M_s = int(get("MAX_FLOOD_IN_P_M_s", 3))
    NC_LOG_P_M_S = bool(get("NC_LOG_P_M_S", False))
    PM_LOGGR_BOT_API_ID = get("BOTLOG_CHATID", None)
    if PM_LOGGR_BOT_API_ID:
        PM_LOGGR_BOT_API_ID = int(PM_LOGGR_BOT_API_ID)
    DB_URI = get("DATABASE_URL", None)
    NO_OF_BUTTONS_DISPLAYED_IN_H_ME_CMD = int(
        get("NO_OF_BUTTONS_DISPLAYED_IN_H_ME_CMD", 5)
    )
    COMMAND_HAND_LER = get("COMMAND_HAND_LER", "\\.")
    SUDO_USERS = set(int(x) for x in get("SUDO_USERS", "967883138").split())
    VERY_STREAM_LOGIN = get("VERY_STREAM_LOGIN", None)
    VERY_STREAM_KEY = get("VERY_STREAM_KEY", None)
    GROUP_REG_SED_EX_BOT_S = get(
        "GROUP_REG_SED_EX_BOT_S", r"(regex|moku|BananaButler_|rgx|l4mR)bot"
    )
    TEMP_DIR = get("TEMP_DIR", None)
    CHANNEL_ID = int(get("CHANNEL_ID", -100))
    CHROME_DRIVER = get(
        "CHROME_DRIVER", "/app/.chromedriver/bin/chromedriver"
    )
    GOOGLE_CHROME_BIN = get(
        "GOOGLE_CHROME_BIN", "/app/.apt/usr/bin/google-chrome"
    )
    G_DRIVE_CLIENT_ID = get("G_DRIVE_CLIENT_ID", None)
    G_DRIVE_CLIENT_SECRET = get("G_DRIVE_CLIENT_SECRET", None)
    GDRIVE_FOLDER_ID = get("GDRIVE_FOLDER_ID", None)
    YOUTUBE_API_KEY = get("YOUTUBE_API_KEY", None)
    GDRIVE_FOLDER_ID = get("GDRIVE_FOLDER_ID", None)
    MONGO_URI = get("MONGO_URI", None)
    LYDIA_API = get("LYDIA_API", None)
    LOGGER = True
    BOTLOG = sb(get("BOTLOG", "False"))
    LOGSPAMMER = sb(get("LOGSPAMMER", "False"))
    ACTIVATE_ASSISTANT = get("ACTIVATE_ASSISTANT", "False")
    AUTOPIC_COMMENT = get("AUTOPIC_COMMENT", "")
    AUTOPIC_FONT_COLOUR = get("AUTOPIC_FONT_COLOUR", "")
    AUTOPIC_FONT = get("AUTOPIC_FONT", "")
    AUTO_BIO = get("AUTO_BIO", "")
    PM_AUTO_BAN = sb(get("PM_AUTO_BAN", "False"))
    CONSOLE_LOGGER_VERBOSE = sb(get("CONSOLE_LOGGER_VERBOSE", "False"))
    DB_URI = get("DATABASE_URL", None)
    OCR_SPACE_API_KEY = get("OCR_SPACE_API_KEY", None)
    REM_BG_API_KEY = get("REM_BG_API_KEY", None)
    MONGO_URI = get("MONGO_URI", "")
    CHROME_DRIVER = "/usr/bin/chromedriver"
    GOOGLE_CHROME_BIN = "/usr/bin/google-chrome"
    OPEN_WEATHER_MAP_APPID = get("OPEN_WEATHER_MAP_APPID", None)
    ANTI_SPAMBOT = sb(get("ANTI_SPAMBOT", "False"))
    ANTI_SPAMBOT_SHOUT = sb(get("ANTI_SPAMBOT_SHOUT", "False"))
    F_BAN_LOGGER_GROUP = get("F_BAN_LOGGER_GROUP", None)
    HEROKU_MEMEZ = sb(get("HEROKU_MEMEZ", "False"))
    HEROKU_APP_NAME = get("HEROKU_APP_NAME", None)
    HEROKU_API_KEY = get("HEROKU_API_KEY", None)
    YOUTUBE_API_KEY = get("YOUTUBE_API_KEY", None)
    ALIVE_NAME = get("ALIVE_NAME", None)
    AUTONAME = get("AUTONAME", None)
    COUNTRY = str(get("COUNTRY", "India"))
    TZ_NUMBER = int(get("TZ_NUMBER", 1))
    FBAN_REASON = get("FBAN_REASON", None)
    FBAN_USER = get("FBAN_USER", None)
    CLEAN_WELCOME = sb(get("CLEAN_WELCOME", "True"))
    CUSTOM_PMPERMIT = get("CUSTOM_PMPERMIT", None)
    CUSTOM_STICKER_PACK_NAME = get("CUSTOM_STICKER_PACK_NAME", None)
    CUSTOM_ANIMATED_PACK_NAME = get("CUSTOM_ANIMATED_PACK_NAME", None)
    BIO_PREFIX = get("BIO_PREFIX", None)
    DEFAULT_BIO = get("DEFAULT_BIO", None)
    G_DRIVE_CLIENT_ID = get("G_DRIVE_CLIENT_ID", None)
    G_DRIVE_CLIENT_SECRET = get("G_DRIVE_CLIENT_SECRET", None)
    G_DRIVE_AUTH_TOKEN_DATA = get("G_DRIVE_AUTH_TOKEN_DATA", None)
    GDRIVE_FOLDER_ID = get("GDRIVE_FOLDER_ID", None)
    TEMP_DOWNLOAD_DIRECTORY = get("TEMP_DOWNLOAD_DIRECTORY", "./downloads")
    LASTFM_API = get("LASTFM_API", None)
    LASTFM_SECRET = get("LASTFM_SECRET", None)
